In [1]:
# This forces a reload of any external library file if it changes.  
# Useful when developing external libraries since otherwise Jupyter 
# will not re-import any library without restarting the python kernel.

%load_ext autoreload
%autoreload 2

In [2]:
import COVIDlib.data_IO as io
import numpy as np
import pandas as pd
#import Generate_Test_Data

ClayFIPS = 27027
CassFIPS = 38017
MNFIPS = 27
NDFIPS = 38

In [3]:
# Creating the data frames
sumFrame, hospFrame = io.GetIMHEDataFrames('test_data/TEST_imhe_summary.csv', 'test_data/TEST_imhe_hospitalizations.csv')

stateFrame, countyFrame = io.GetCDRDataFrames('test_data/TEST_statelevel_combinedCDR.csv', 'test_data/TEST_countylevel_combinedCDR.csv')

In [6]:
# Testing the functions
mnEquip = io.GetEquipData(MNFIPS, sumFrame)
mnHosp = io.GetHospitalizationData(MNFIPS, hospFrame)

ndEquip = io.GetEquipData(NDFIPS, sumFrame)
ndHosp = io.GetHospitalizationData(NDFIPS, hospFrame)

In [8]:
mnEquip

,FIPS,state,peak_bed_day_mean,peak_bed_day_lower,peak_bed_day_upper,peak_icu_bed_day_mean,peak_icu_bed_day_lower,peak_icu_bed_day_upper,peak_vent_day_mean,peak_vent_day_lower,peak_vent_day_upper,all_bed_capacity,icu_bed_capacity,all_bed_usage,icu_bed_usage
0,27,Minnesota,2020-05-15,2020-05-01,2020-06-15,2020-05-15,2020-05-01,2020-06-15,2020-05-15,2020-05-01,2020-06-15,2000,200,2000,200

In [9]:
mnHosp

,FIPS,state,dates,allbed_mean,allbed_lower,allbed_upper,ICUbed_mean,ICUbed_lower,ICUbed_upper,InvVen_mean,InvVen_lower,InvVen_upper
0,27,Minnesota,"[2020-03-22, 2020-03-23, 2020-03-24, 2020-03-2...","[0.0, 1000.0, 2000.0, 3000.0, 4000.0, 5000.0, ...","[0.0, 900.0, 1800.0, 2700.0, 3600.0, 4500.0, 5...","[0.0, 1100.0, 2200.0, 3300.0, 4400.0, 5500.0, ...","[0.0, 100.0, 200.0, 300.0, 400.0, 500.0, 600.0...","[0.0, 90.0, 180.0, 270.0, 360.0, 450.0, 540.0,...","[0.0, 110.0, 220.0, 330.0, 440.0, 550.0, 660.0...","[0.0, 50.0, 100.0, 150.0, 200.0, 250.0, 300.0,...","[0.0, 45.0, 90.0, 135.0, 180.0, 225.0, 270.0, ...","[0.0, 50.0, 100.0, 150.0, 200.0, 250.0, 300.0,..."

In [10]:
ndEquip

,FIPS,state,peak_bed_day_mean,peak_bed_day_lower,peak_bed_day_upper,peak_icu_bed_day_mean,peak_icu_bed_day_lower,peak_icu_bed_day_upper,peak_vent_day_mean,peak_vent_day_lower,peak_vent_day_upper,all_bed_capacity,icu_bed_capacity,all_bed_usage,icu_bed_usage
1,38,North Dakota,2020-06-15,2020-06-01,2020-07-15,2020-06-15,2020-06-01,2020-07-15,2020-06-15,2020-06-01,2020-07-15,1000,100,1000,100

In [11]:
# Viewing the functions
ndHosp

# io.GetCDRState(MNFIPS, stateFrame)
# io.GetCDRCounty(CassFIPS, countyFrame)

,FIPS,state,dates,allbed_mean,allbed_lower,allbed_upper,ICUbed_mean,ICUbed_lower,ICUbed_upper,InvVen_mean,InvVen_lower,InvVen_upper
1,38,North Dakota,"[2020-03-22, 2020-03-23, 2020-03-24, 2020-03-2...","[0.0, 500.0, 1000.0, 1500.0, 2000.0, 2500.0, 3...","[0.0, 450.0, 900.0, 1350.0, 1800.0, 2250.0, 27...","[0.0, 550.0, 1100.0, 1650.0, 2200.0, 2750.0, 3...","[0.0, 50.0, 100.0, 150.0, 200.0, 250.0, 300.0,...","[0.0, 45.0, 90.0, 135.0, 180.0, 225.0, 270.0, ...","[0.0, 55.0, 110.0, 165.0, 220.0, 275.0, 330.0,...","[0.0, 25.0, 50.0, 75.0, 100.0, 125.0, 150.0, 1...","[0.0, 22.0, 45.0, 67.0, 90.0, 112.0, 135.0, 15...","[0.0, 25.0, 50.0, 75.0, 100.0, 125.0, 150.0, 1..."